/*const story = [
  "Este é o homem invisível. Pinta-o de transparente.",
  "Esta página tem um fantasma. Consegues vê-lo? Pinta-o de nenhuma cor.",
  "Isto é o interior de um balão. Usa a cor do ar para a colorir.",
  "Aqui está o infinito. Preenche-o.",
  "Isto é uma mentira. Finge que a estás a pintar.",
  "Isto é um buraco. Enche-o de coisa nenhuma.",
  "Este é o teu amigo imaginário. Pinta-o de uma cor que só tu consegues ver.",
  "Aqui está o silêncio. Usa uma cor muda para o preencher.",
  "O copo está meio cheio. Pinta esta metade vazia.",
  "Estas páginas estão cheias de amor. Pinta-as da cor que quiseres, mas pinta-as atá ao fim. Ninguém disse que ia ser fácil.",
  "Isto é um número multiplicado por zero. Usa uma caneta vazia para o preencher.",
  "Isto é uma coisa de que não te lembras. Pinta-a de uma cor que não consigas ver.",
  "Dois homens estão a transportar este vidro de uma janela para o outro lado da rua. Pinta o vidro da cor do vidro.",
  "Estes são os últimos segundos antes do big bang. Usa tinta de vácuo para os colorir.",
  "Isto é uma série de medos infundados. Podes colori-los como quiseres, mas se pintares fora das linhas esses medos tornam-se reais.",
  "Nesta página está um camuflado para a neve. Pinta-o, mas só se tiveres a certeza de que não nenhum urso polar por perto.",
  "Isto é aquilo que tu eras antes de nasceres. Pinta com a cor daquilo que vais ser quando deixares de existir.",
  "Nesta página está um camaleão. Um camaleão muito bom, completamente camuflado. Pinta-o da cor que o rodeia.",
];
*/
const story = [
  "This is the invisible man. Paint him transparent.",
  "This page has a ghost. Can you see it? Paint it with the none color.",
  "This is the inside of a balloon. Use the color of the air to color it.",
  "Here is infinity. Fill it.",
  "This is a lie. Pretend you are painting it.",
  "This is a hole. Fill it with nothing.",
  "This is your imaginary friend. Paint them with a color that only you can see.",
  "Here's the silence. Use a muted color to fill it.",
  "The glass is half full. Paint this half empty.",
  "These pages are full of love. Paint them any color you want, but paint them to the end. Nobody said it was going to be easy.",
  "This is a number multiplied by zero. Use an empty pen to fill it.",
  "This is something you don't remember. Paint it with a color you can't see.",
  "Two men are transporting this glass from a window to the other side of the street. Paint the glass the color of the glass.",
  "These are the last seconds before the big bang. Use vacuum paint to color them.",
  "This is a series of unfounded fears. You can color them however you want, but if you paint outside the lines those fears become real.",
  "On this page is a snow camouflage. Paint it, but only if you are sure there are no polar bears around.",
  "This is what you were before you were born. Paint with the color of what you will be when you cease to exist.",
  "On this page is a chameleon. A very good chameleon, completely camouflaged. Paint it the color that surrounds it.",
];

export default story;